### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by DarknightCanada** [MaorSabag/SideLoadingDLL#1]
`PS C:\Users\wsl\Downloads\SideLoadingDLL-main\SideLoadingDLL-main> python .\make.py -h
  File "C:\Users\wsl\Downloads\SideLoadingDLL-main\SideLoadingDLL-main\make.py", line 396
    if not os.path.exists('Output'):
TabError: inconsistent use of tabs and spaces in indentation`

**Comment by MaorSabag** [comment]
Pushed fixes.
Should work fine now.
